### ISSUE TITLE
Error while reshuffling matrices

### ISSUE THREAD

**Issue by ddomingof** [philipmorrisintl/NPA#2]
I tried the example stated:

`data(COPD1)`
`net.apopto <- load_model('Mm', 'CFA', 'Apoptosis')`
`npa <- compute_npa(COPD1, net.apopto, verbose = TRUE)`

and I get the following error:

Error in ql %*% W : requires numeric/complex matrix/vector arguments at the following line
https://github.com/pmpsa-hpc/NPA/blob/4480030156e000a98cc0800a9719ad6b45b0cea7/R/computeNPA.R#L190

I could make a workaround by checking if each of the shuffles was returning a NULL matrix.
Apparently, (not sure why this occurs) some of the shuffles contain a NULL matrix and that leads to the error.

**Comment by sgubianpm** [comment]
Dear @ddomingof ,
Thanks a lot. I cannot reproduce this one. Are you using Windows or OSX? This works fine on Linux and tests are passing for this part. Cheers!

**Comment by ddomingof** [comment]
Dear @sgubianpm,
OSX with R 3.5.1. I will check again and close the issue if it works. Thanks for the info

**Comment by ddomingof** [comment]
Still there running it with Linux. Which version of R are you using? 3.6?

**Comment by sgubianpm** [comment]
Dear @ddomingof,
I am using R-3.5.1 (and need to commit the DESCRIPTION file mentioning R-3.6, otherwise this creates an error in BiocCheck as the next release of Bioc will be associated with R-3.6 (still in dev)).
I am changing the DESCRIPTION file on my workstation as I did not install R-3.6, but if this issue occurs on R-3.6 only, I would install it to understand how to fix it.

**Comment by ddomingof** [comment]
I see... It's weird because I tried in different systems with 3.5.1 and I got the same problem in all. But this particular line does not require any dependency, isn't? I don't see where the problem may come from.

**Comment by sgubianpm** [comment]
Dear @ddomingof,
I have fixed the issue. It comes from the NPAModels ``getLQ`` function.
I needed to replace:
```
is(class(ql3inv), "try-error")
```
because it does not work as expected,  by
```
inherits(ql3inv, "try-error")
```
You need to reinstall NPAModels with from the latest commit and call ``preprocessNetworks``.
